[@SarahJamieLewis on Decentralization]
Link = ["https://twitter.com/SarahJamieLewis/status/1029212002953060352?s=19"]
Description = "Since many of my twitter fights devolve into people saying 'but it's actually not centralized tho', let's talk about wtf decentralization actually means.\n\nThis tweetstorm has background reading."
Tags = ["decentralization", "twitter"]

[How to Disincentivize Large Bitcoin Mining Pools]
Link = ["http://hackingdistributed.com/2014/06/18/how-to-disincentivize-large-bitcoin-mining-pools/"]
Description = "Recently, the GHash mining pool breached Bitcoin etiquette to become a 55% miner for Bitcoin [*]. This collapsed the key value proposition of Bitcoin, namely, its decentralization. In turn, there has been considerable criticism and backlash. Many people in the community, including us, have noted that etiquette or the good will of miners are not sufficient to keep monopolies at bay, and called for technical measures to disincentivize large mining pools."
Tags = ["bitcoin", "mining", "decentralization"]

[Decenturion]
Link = ["https://decenturion.com"]
Description = "A decentralized state built on blockchain\n\n'Decenturion is a rapidly developing state that has leveraged the complex of cutting-edge technologies to build an effective economy and a progressive society.'"
Tags = ["decentralization", "decentralized-state"]

[@Melt_Dem on Decentralization]
Link = ["https://twitter.com/Melt_Dem/status/1031190564639830016"]
Description = "1/ decentralization is a myth. we use 'decentralized' without any specificity as to what that *actually* means. let's untangle the idea of decentralization. i developed a basic grid that breaks it down at the protocol, network, and app layer (dated april 2018)"
Tags = ["decentralization", "twitter"]

[@SarahJamieLewis on Federation]
Link = ["https://twitter.com/SarahJamieLewis/status/1031301941664440321"]
Description = "Me: Federation is a bad model.\nPeople: You're against decentralization! Fascist!\nMe: No, I want *more* decentralization, more equal trust distribution.\nPeople: 'If ideal social power were perfect equality, we'd be ants.'"
Tags = ["decentralization", "federation", "twitter"]

[r/decentralization Discord Server]
Link = ["https://discord.gg/zkF6aNQ"]
Description = "Our mission is to liberate ourselves from centralized entities and help the world take back control, and further perpetuate political, fiscal, and economic Decentralization. We are dedicated to making sure that our group is of quality and a constructive place to work together.\n\nPlease Check out our subreddit here https://www.reddit.com/r/decentralization/"
Tags = ["decentralization", "discord"]

[@nic_carter on Decentralization]
Link = ["https://twitter.com/nic__carter/status/1008419100136296448"]
Description = "My thoughts have evolved a bit since this, but the big idea is the same. You have decentralization of validation ('node level'), block formation ('protocol level'), and decision-making and update-management ('political'). Your system isn’t decentralized without all three."
Tags = ["decentralization", "twitter"]

[Free Company — THE DECENTRALIZED FUTURE OF WORK]
Link = ["https://www.tokendaily.co/blog/free-company"]
Description = "The path forward is to create a system that can match this pent up supply of talent with the rampant demand from the projects. An entity or entities that will bring together top talent with top projects in the space, allowing contributors to work broadly across the ecosystem and allowing projects to gain from the spirit of open source. The solution is a Free Company that can be contracted to work on projects collaboratively across the space."
Tags = ["decentralization", "work-in-crypto"]

[Quantifying Decentralization]
Link = ["https://news.earn.com/quantifying-decentralization-e39db233c28e"]
Description = "The primary advantage of Bitcoin and Ethereum over their legacy alternatives is widely understood to be decentralization. However, despite the widely acknowledged importance of this property, most discussion on the topic lacks quantification."
Tags = ["decentralization"]

[@we_are_cordite on Decentralization]
Link = ["https://twitter.com/we_are_cordite/status/1008985334187773952"]
Description = "One way to measure decentralisation, is by measuring the benefits. But do you think we should look at the technology and the business separately when we consider decentralisation? Or does one influence the other?"
Tags = ["decentralization", "twitter", "image"]

[The Case for Decentralization]
Link = ["https://medium.com/@rickcrook/the-case-for-de-centralisation-1ac14935a3fc"]
Descriptoin = "2016 was all about performance and scalability, 2017 was all about security. These are technical challenges. The harder challenges are the social and political ones. One of the key unsolved challenges is the de-centralised business model. I have consistently messaged that ‘there is no point replacing one centralised business model with another’. I believe 2018 will be the year that many in the blockchain domain wake up to the fact that there is little point distributing the technology if you are not going to distribute the business model. This challenge remains within all the blockchain projects I am focused on."
Tags = ["decentralization"]

[The Death of 'Decentralization']
Link = ["https://www.tokendaily.co/blog/the-death-of-decentralization"]
Description = "It's no secret that 'decentralization' has been reduced to a marketing buzzword, and it's losing meaning through its misuse. Your project or idea may have some qualities that decentralization facilitates (censorship resistance, immutability, accessibility, etc) — but it is not 'decentralized.' This post has been inspired by a few conversations and two articles that have recently surfaced."
Tags = ["decentralization"]

[@lopp on Decentralization]
Link = ["https://twitter.com/lopp/status/1028092364559208448"]
Description = "Measuring centralization can be an informative academic exercise, but IMO the only way to know if a network is sufficiently decentralized is to attack it. If it can withstand attacks from nation states, it's sufficiently decentralized."
Tags = ["decentralization", "twitter"]


https://medium.com/@sytaylor/what-is-a-decentralised-exchange-e2b86e844fe9
---

https://fieldnotes.resistant.tech/defensive-decentralization/

---

https://coinjournal.net/introducing-decenturion-a-decentralized-state-built-on-blockchain/

---

https://twitter.com/SarahJamieLewis/status/1031301941664440321

---

https://coincenter.org/entry/what-could-decentralization-mean-in-the-context-of-the-law

---

https://medium.com/distributed-economy/what-is-the-difference-between-decentralized-and-distributed-systems-f4190a5c6462

---

https://medium.com/@jbackus/resistant-protocols-how-decentralization-evolves-2f9538832ada

---

https://twitter.com/backus/status/1039701785789620224

---

https://arxiv.org/pdf/1809.06528.pdf
