https://twitter.com/SarahJamieLewis/status/1029212002953060352?s=19

---

http://hackingdistributed.com/2014/06/18/how-to-disincentivize-large-bitcoin-mining-pools/

---

https://cointelegraph.com/news/binance-releases-demo-of-decentralized-exchange

---

https://coinjournal.net/introducing-decenturion-a-decentralized-state-built-on-blockchain/

---

https://twitter.com/Melt_Dem/status/1031190564639830016

---

https://twitter.com/SarahJamieLewis/status/1031301941664440321

---

https://discord.gg/zkF6aNQ

---

https://twitter.com/nic__carter/status/1008419100136296448

---

https://www.tokendaily.co/blog/free-company

---

https://twitter.com/sytaylor/status/1026155964481851392

---

https://twitter.com/lopp/status/1028092364559208448

---

https://medium.com/zkcapital/handshake-ens-and-decentralized-naming-services-explained-2e69a1ca1313

---

https://fieldnotes.resistant.tech/defensive-decentralization/

---

https://coinjournal.net/introducing-decenturion-a-decentralized-state-built-on-blockchain/

---

https://twitter.com/SarahJamieLewis/status/1031301941664440321

---

https://coincenter.org/entry/what-could-decentralization-mean-in-the-context-of-the-law

---

https://medium.com/distributed-economy/what-is-the-difference-between-decentralized-and-distributed-systems-f4190a5c6462

---

https://medium.com/@jbackus/resistant-protocols-how-decentralization-evolves-2f9538832ada

---

https://twitter.com/backus/status/1039701785789620224

---

https://arxiv.org/pdf/1809.06528.pdf
