[@SarahJamieLewis on Decentralization]
Link = ["https://twitter.com/SarahJamieLewis/status/1029212002953060352?s=19"]
Description = "Since many of my twitter fights devolve into people saying 'but it's actually not centralized tho', let's talk about wtf decentralization actually means.\n\nThis tweetstorm has background reading."
Tags = ["decentralization", "twitter"]

[How to Disincentivize Large Bitcoin Mining Pools]
Link = ["http://hackingdistributed.com/2014/06/18/how-to-disincentivize-large-bitcoin-mining-pools/"]
Description = "Recently, the GHash mining pool breached Bitcoin etiquette to become a 55% miner for Bitcoin [*]. This collapsed the key value proposition of Bitcoin, namely, its decentralization. In turn, there has been considerable criticism and backlash. Many people in the community, including us, have noted that etiquette or the good will of miners are not sufficient to keep monopolies at bay, and called for technical measures to disincentivize large mining pools."
Tags = ["bitcoin", "mining", "decentralization"]

[Decenturion]
Link = ["https://decenturion.com"]
Description = "A decentralized state built on blockchain\n\n'Decenturion is a rapidly developing state that has leveraged the complex of cutting-edge technologies to build an effective economy and a progressive society.'"
Tags = ["decentralization", "decentralized-state"]

[@Melt_Dem on Decentralization]
Link = ["https://twitter.com/Melt_Dem/status/1031190564639830016"]
Description = "1/ decentralization is a myth. we use "decentralized" without any specificity as to what that *actually* means. let's untangle the idea of decentralization. i developed a basic grid that breaks it down at the protocol, network, and app layer (dated april 2018)"
Tags = ["decentralization", "twitter"]

[@SarahJamieLewis on Federation]
Link = ["https://twitter.com/SarahJamieLewis/status/1031301941664440321"]
Description = "Me: Federation is a bad model.\nPeople: You're against decentralization! Fascist!\nMe: No, I want *more* decentralization, more equal trust distribution.\nPeople: 'If ideal social power were perfect equality, we'd be ants.'"
Tags = ["decentralization", "federation", "twitter"]

[r/decentralization Discord Server]
Link = ["https://discord.gg/zkF6aNQ"]
Description = "Our mission is to liberate ourselves from centralized entities and help the world take back control, and further perpetuate political, fiscal, and economic Decentralization. We are dedicated to making sure that our group is of quality and a constructive place to work together.\n\nPlease Check out our subreddit here https://www.reddit.com/r/decentralization/"
Tags = ["decentralization", "discord"]



https://twitter.com/nic__carter/status/1008419100136296448

---

https://www.tokendaily.co/blog/free-company

---

https://twitter.com/sytaylor/status/1026155964481851392

---

https://twitter.com/lopp/status/1028092364559208448

---

https://medium.com/zkcapital/handshake-ens-and-decentralized-naming-services-explained-2e69a1ca1313

---

https://fieldnotes.resistant.tech/defensive-decentralization/

---

https://coinjournal.net/introducing-decenturion-a-decentralized-state-built-on-blockchain/

---

https://twitter.com/SarahJamieLewis/status/1031301941664440321

---

https://coincenter.org/entry/what-could-decentralization-mean-in-the-context-of-the-law

---

https://medium.com/distributed-economy/what-is-the-difference-between-decentralized-and-distributed-systems-f4190a5c6462

---

https://medium.com/@jbackus/resistant-protocols-how-decentralization-evolves-2f9538832ada

---

https://twitter.com/backus/status/1039701785789620224

---

https://arxiv.org/pdf/1809.06528.pdf
