["A Thorough Introduction to Distributed Systems"]
Link = ["https://hackernoon.com/a-thorough-introduction-to-distributed-systems-3b91562c9b3c"]
Description = "With the ever-growing technological expansion of the world, distributed systems are becoming more and more widespread. They are a vast and complex field of study in computer science.\n\nThis article aims to introduce you to distributed systems in a basic manner, showing you a glimpse of the different categories of such systems while not diving deep into the details."
Tags = ["distributed-systems"]

["awesome-distributed-systems"]
Link = ["https://github.com/theanalyst/awesome-distributed-systems"]
Description = "A (hopefully) curated list on awesome material on distributed systems, inspired by other awesome frameworks like awesome-python. Most links will tend to be readings on architecture itself rather than code itself."
Tags = ["literature", "awesome", "distributed-systems"]

["Awesome Consensus"]
Link = ["https://github.com/dgryski/awesome-consensus"]
Description = "A curated selection of artisanal consensus algorithms and hand-crafted distributed lock services."
Tags = ["consensus-algorithms", "distributed-systems", "awesome"]

["Simpler consensus with Raft"]
Link = ["http://www.goodmath.org/blog/2015/02/14/simpler-consensus-with-raft/"]
Description = "A few weeks ago, I wrote about Paxos, which is (at least in my experience), the most widely used algorithm for consensus in distributed systems. I’m a huge fan of Paxos – I think that it’s a remarkably elegant system.\n\nBut Paxos does have its problem."
Tags = ["consensus-algorithms"]

["Learning about Distributed Systems"]
Link = ["http://alvaro-videla.com/2015/12/learning-about-distributed-systems.html"]
Description = "Apart from the abundance of papers and research material, as mentioned above, there are also lots books. Having bought quite a few of them and read chapters here and there, I started to see that a book that had a promising title was quite unrelated to what I was looking for, or that the content didn’t directly target the problems I would have liked to solve. Therefore, I would like to go over what I think are the main concepts of distributed systems, citing papers, books or resources where one can learn about them."
Tags = ["distributed-systems"]
