[The Untold History of Blockchain]
Link = ["https://www.linkedin.com/pulse/untold-history-blockchain-petri-basson/"]
Description = "To get an idea of the building blocks that the blockchain is built on, you have to understand the history of 3 things:\n\n    Encryption;\n    Open Source software development; and\n    Peer to peer sharing"
Tags = ["bitcoin", "history", "encryption", "p2p", "open-source"]

[A Brief History of Digital Currencies]
Link = ["https://ebrary.net/7927/education/brief_history_digital_currencies"]
Description = "A Brief History of Digital Currencies\n\nThe birth of the Internet led many, including economist Milton Friedman, to assume that the invention of some sort of digital money would soon follow. Arguments in favor of digital money were numerous. One obvious benefit realized early on was that it might help prevent counterfeiting:\n\nThe advent of high-quality color copiers threatens the security of paper money. The demands of guarding it make paper money expensive. The hassles of handling it (such as vending machines) make paper money undesirable. The use of credit cards and ATM cards is becoming increasingly popular, but those systems lack adequate privacy or security against fraud, resulting in a demand for efficient electronic-money systems to prevent fraud and also to protect user privacy.\n\n—Jorg Kienzle and Adrian Perrig in 'Digital Money: A divine gift or Satan's malicious tool?' (1996)"
Tags = ["history", "virtual-currency"]

[Bitcoin's Academic Pedigree]
Link = ["https://cacm.acm.org/magazines/2017/12/223058-bitcoins-academic-pedigree/fulltext"]
Description = "If you have read about bitcoin in the press and have some familiarity with academic research in the field of cryptography, you might reasonably come away with the following impression: Several decades' worth of research on digital cash, beginning with David Chaum,10,12 did not lead to commercial success because it required a centralized, bank-like server controlling the system, and no banks wanted to sign on. Along came bitcoin, a radically different proposal for a decentralized cryptocurrency that did not need the banks, and digital cash finally succeeded."
Tags = ["history", "bitcoin", "academia", "encryption", "research"]

[Satoshi Nakamoto Institute]
Link = ["https://nakamotoinstitute.org/"]
Description = "The Satoshi Nakamoto Institute is eager to share with the world the best ideas past, present, and future in cryptography, distributed networks, economic freedom, and freedom of information. We are dedicated to curating the best primary source literature that challenge the status quo through technological innovation."
Tags = ["bitcoin", "history", "satoshi", "resources"]

[Satoshi Nakamoto Institute — Literature]
Link = ["https://nakamotoinstitute.org/literature/"]
Description = "Bitcoin was not forged in a vacuum. These works serve to contextualize Bitcoin into the broader story of cryptography and freedom."
Tags = ["bitcoin", "history", "research"]

[@NickSzabo4 on Layer2 Scaling]
Link = ["https://twitter.com/NickSzabo4/status/1012373493252419584"]
Description = "My bit gold design in 1998 was 2-layer: bit gold for settlement, Chaumian e-cash for a privacy-enhanced payments layer. I've always thought of Bitcoin as evolving into a settlements-and-large-payments layer that in the long term needed a layer 2 for consumer payments."
Tags = ["history", "bitcoin", "scaling", "layer2", "twitter"]

[Genesis Block Newspaper]
Link = ["https://www.thetimes03jan2009.com/", "https://www.thetimes03jan2009.com/wp-content/uploads/2015/03/genesis-block-newspaper-bitcoin.jpg"]
Description = "The only two remaining verified complete copies of this newspaper were acquired from the London National Archives on January 14, 2014. The newspapers come in a complete set with both the cover and the entire newspaper included.\n\nBoth come with a certificate of authenticity from the archival company, and one comes with an engraved storage folder mentioning the Genesis Block and the Satoshi Nakamoto quote, as well as its relevance to the Bitcoin block chain."
Tags = ["history", "image", "bitcoin"]

[@lopp on Bitcoin History]
Link = ["https://twitter.com/lopp/status/1023689161096785920"]
Description = "Bitcoin whitepaper purists should take note that the following things are NOT described in the whitepaper: \n\nmultisig\n mining pools\n 21M coin cap\n GPU & ASIC mining\n 10 minute block times\n HD address generation\n best chain = cumulative PoW, not longest chain\n and much, much more..."
Tags = ["bitcoin", "history", "bitcoin-whitepaper"]



https://twitter.com/PeterLBrandt/status/1030884169763549184

---

https://www.thestreet.com/investing/bitcoin/bitcoin-history-14686578

---

https://medium.com/@nic__carter/visions-of-bitcoin-4b7b7cbcd24c

---

http://wiki.p2pfoundation.net/Bitcoin#History

---

https://nakamotoinstitute.org/literature/

---

https://twitter.com/dantwany/status/939365748690087936

---

https://twitter.com/pierre_rochard/status/1035635907498532865

---

https://www.blockchainedu.org/education/

---

https://medium.com/@Petri.basson/the-untold-history-of-blockchain-30238a89be5d

---

https://medium.com/@rusty_lightning/the-three-economic-eras-of-bitcoin-d43bf0cf058a

---

https://twitter.com/dantwany/status/939987392496365569

---

https://twitter.com/dantwany/status/939365748690087936

---

https://twitter.com/ericturnr/status/1037095399868297217

---

https://twitter.com/TuurDemeester/status/958882985406758912

---

https://twitter.com/francispouliot_/status/1037379672282152960

---

https://twitter.com/francispouliot_/status/1037358649029668864

---

https://www.forbes.com/sites/michaeldelcastillo/2018/09/06/bitcoin-is-not-dead/#355f465b5bdd

---

https://www.bloomberg.com/view/articles/2018-09-18/bitcoin-stumble-shows-bitmain-a-ghost-of-crises-past?utm_medium=social&utm_source=twitter&utm_content=crypto&utm_campaign=socialflow-organic

---

https://twitter.com/varun_mathur/status/1038107664868208640

---

https://medium.com/tbis-weekly-bits/bitcoins-constitutional-crisis-why-i-support-the-uasf-5b0ab325d8b6

---

https://www.bloomberg.com/view/articles/2018-09-18/bitcoin-stumble-shows-bitmain-a-ghost-of-crises-past

---

https://twitter.com/scott_lew_is/status/1042043969348284417

---

https://stephanlivera.com/2018/09/20/slp23-economic-eras-of-bitcoin-and-lightning-development-with-rusty-russell-of-blockstream/

---

https://twitter.com/notgrubles/status/1043569394901602304

---

https://youtu.be/cagoyF3WePo

---

https://twitter.com/BitcoinErrorLog/status/1044207811603943425

---

https://steemit.com/crypto/@sxiii/oldest-icos

---

https://www.youtube.com/watch?v=EkeCapBOQQ0

---

https://oxt.me/history

---

https://www.bitcoin.kn/legendary/

---

https://www.theinvestorspodcast.com/blog/debt-deflation-italian-style/

---

http://archive.is/H8UGk

---

https://www.wired.com/2016/06/the-uncanny-mind-that-built-ethereum/

---

https://unblock.net/nick-szabo/

---

https://blockchainlibrary.org/category/reading-lists/bitcoin-history/

---

https://www.wsj.com/articles/the-eureka-moment-that-made-bitcoin-possible-1527268025

---

https://nakamotoinstitute.org/trusted-third-parties/

---

https://ebrary.net/7927/education/brief_history_digital_currencies#360
