[The Untold History of Blockchain]
Link = ["https://www.linkedin.com/pulse/untold-history-blockchain-petri-basson/"]
Description = "To get an idea of the building blocks that the blockchain is built on, you have to understand the history of 3 things:\n\n    Encryption;\n    Open Source software development; and\n    Peer to peer sharing"
Tags = ["bitcoin", "history", "encryption", "p2p", "open-source"]

[A Brief History of Digital Currencies]
Link = ["https://ebrary.net/7927/education/brief_history_digital_currencies"]
Description = "A Brief History of Digital Currencies\n\nThe birth of the Internet led many, including economist Milton Friedman, to assume that the invention of some sort of digital money would soon follow. Arguments in favor of digital money were numerous. One obvious benefit realized early on was that it might help prevent counterfeiting:\n\nThe advent of high-quality color copiers threatens the security of paper money. The demands of guarding it make paper money expensive. The hassles of handling it (such as vending machines) make paper money undesirable. The use of credit cards and ATM cards is becoming increasingly popular, but those systems lack adequate privacy or security against fraud, resulting in a demand for efficient electronic-money systems to prevent fraud and also to protect user privacy.\n\n—Jorg Kienzle and Adrian Perrig in 'Digital Money: A divine gift or Satan's malicious tool?' (1996)"
Tags = ["history", "digital-currency"]

[Bitcoin's Academic Pedigree]
Link = ["https://cacm.acm.org/magazines/2017/12/223058-bitcoins-academic-pedigree/fulltext"]
Description = "If you have read about bitcoin in the press and have some familiarity with academic research in the field of cryptography, you might reasonably come away with the following impression: Several decades' worth of research on digital cash, beginning with David Chaum,10,12 did not lead to commercial success because it required a centralized, bank-like server controlling the system, and no banks wanted to sign on. Along came bitcoin, a radically different proposal for a decentralized cryptocurrency that did not need the banks, and digital cash finally succeeded."
Tags = ["history", "bitcoin", "academia", "cryptography", "literature", "research"]

[Satoshi Nakamoto Institute]
Link = ["https://nakamotoinstitute.org/"]
Description = "The Satoshi Nakamoto Institute is eager to share with the world the best ideas past, present, and future in cryptography, distributed networks, economic freedom, and freedom of information. We are dedicated to curating the best primary source literature that challenge the status quo through technological innovation."
Tags = ["bitcoin", "history", "satoshi", "resources"]

[Satoshi Nakamoto Institute — Literature]
Link = ["https://nakamotoinstitute.org/literature/"]
Description = "Bitcoin was not forged in a vacuum. These works serve to contextualize Bitcoin into the broader story of cryptography and freedom."
Tags = ["bitcoin", "history", "literature", "research"]

[@NickSzabo4 on Layer2 Scaling]
Link = ["https://twitter.com/NickSzabo4/status/1012373493252419584"]
Description = "My bit gold design in 1998 was 2-layer: bit gold for settlement, Chaumian e-cash for a privacy-enhanced payments layer. I've always thought of Bitcoin as evolving into a settlements-and-large-payments layer that in the long term needed a layer 2 for consumer payments."
Tags = ["history", "bitcoin", "scaling", "layer2", "twitter"]

[Genesis Block Newspaper]
Link = ["https://www.thetimes03jan2009.com/", "https://www.thetimes03jan2009.com/wp-content/uploads/2015/03/genesis-block-newspaper-bitcoin.jpg"]
Description = "The only two remaining verified complete copies of this newspaper were acquired from the London National Archives on January 14, 2014. The newspapers come in a complete set with both the cover and the entire newspaper included.\n\nBoth come with a certificate of authenticity from the archival company, and one comes with an engraved storage folder mentioning the Genesis Block and the Satoshi Nakamoto quote, as well as its relevance to the Bitcoin block chain."
Tags = ["history", "image", "bitcoin"]

[@lopp on Bitcoin History]
Link = ["https://twitter.com/lopp/status/1023689161096785920"]
Description = "Bitcoin whitepaper purists should take note that the following things are NOT described in the whitepaper: \n\nmultisig\n mining pools\n 21M coin cap\n GPU & ASIC mining\n 10 minute block times\n HD address generation\n best chain = cumulative PoW, not longest chain\n and much, much more..."
Tags = ["bitcoin", "history", "bitcoin-whitepaper"]

[@ericturnr — Research Lead at Messari]
Link = ["https://twitter.com/ericturnr"
Description = "Research lead at @MessariCrypto. Striving for a more transparent and self-regulating cryptoasset community. CFA Charterholder."
Tags = ["research", "messari", "twitter"]

[@PeterLBrandt on 'Bubbles']
Link = ["https://twitter.com/PeterLBrandt/status/1030884169763549184"]
Description = "Us old-timers always considered a decline greater than 80% to be a bubble that popped. Most altcoins must be legitimately considered as bubbles that popped. The dead-cat bounces from the resulting decimation can be wicked."
Tags = ["history", "trading", "twitter"]

[Bitcoin History: Timeline, Origins and Founder]
Link = ["https://www.thestreet.com/investing/bitcoin/bitcoin-history-14686578"]
Description = "The history of Bitcoin has been a turbulent one to say the least, and right now we're in one of the most turbulent periods in its history, as it has spent the entirety of 2018 falling further and further from its peak value of nearly $20,000 in December 2017.\n\nBut something as uncertain as Bitcoin (and cryptocurrency in general) was never going to be smooth sailing. Many tried a cryptographed digital currency before it, and they weren't able to fully crack it. Since Bitcoin became a reality nearly a decade ago, there have been some high highs and some low lows. For some Bitcoin owners, that's part of the appeal.\n\nBut how did we get to where we are today with Bitcoin? How did it begin, what were its forebearers, and what have been the unexpected turns of the Bitcoin journey? Let's take a walk through the timeline and find out."
Tags = ["bitcoin", "history"]

[Visions of Bitcoin—How major Bitcoin narratives changed over time]
Link = ["https://medium.com/@nic__carter/visions-of-bitcoin-4b7b7cbcd24c"]
Description = "Perhaps the most enduring source of conflict within the Bitcoin community derives from incompatible visions of what Bitcoin is and should become. Businesses building on Bitcoin, believing it a cheap global payments network, eventually became nonviable when blocks filled up in 2017. They weren’t necessarily wrong, they just had a vision of the world that ended up being a minority view within the Bitcoin community, and was ultimately not expressed by the protocol on their desired timeline."
Tags = ["bitcoin", "history"]

[Bitcoin History — p2pfoundation]
Link = ["http://wiki.p2pfoundation.net/Bitcoin#History"]
Description = "The small band of early bitcoiners all shared the communitarian spirit of an open source software project. Gavin Andresen, a coder in New England, bought 10,000 bitcoins for $50 and created a site called the Bitcoin Faucet, where he gave them away for the hell of it. Laszlo Hanyecz, a Florida programmer, conducted what bitcoiners think of as the first real-world bitcoin transaction, paying 10,000 bitcoins to get two pizzas delivered from Papa John’s. (He sent the bitcoins to a volunteer in England, who then called in a credit card order transatlantically.) A farmer in Massachusetts named David Forster began accepting bitcoins as payment for alpaca socks"
Tags = ["bitcoin", "history"]

[P2P Foundation Wiki]
Link = ["http://wiki.p2pfoundation.net/"]
Description = "The P2P Foundation is an international organization focused on studying, researching, documenting and promoting peer to peer practices in a very broad sense. This wiki is our knowledge commons. Our motto is "Together we know everything, together we have everything", i.e. pooling our resources through commons, creates prosperity for all. We document thousands of initiatives going in that direction on order to create 'Hope with evidence'."
Tags = ["resources", "p2p", "history", "bitcoin", "decentralization"]

["Digital Cash and Monetary Freedom" (1996)]
Link = [ "http://web.archive.org/web/19971210185701/http://info.isoc.org:80/HMP/PAPER/136/abst.html"]
Description = "Much has been published recently about the awesome promises of electronic commerce and trade on the Internet if only a reliable, secure mechanism for value exchange could be developed. This paper describes the differences between mere encrypted credit card schemes and true digital cash, which presents a revolutionary opportunity to transform payments. The nine key elements of an electronic, digital cash are outlined and a tenth element is proposed which would embody digital cash with a non-political unit of value."
Tags = ["history", "digital-currency", "literature"]

[The Original 'I AM HODLING' Bitcointalk Post]
Link = "https://bitcointalk.org/index.php?topic=375643.0"
Description = "I type d that tyitle twice because I knew it was wrong the first time.  Still wrong.  w/e.  GF's out at a lesbian bar, BTC crashing WHY AM I HOLDING? I'LL TELL YOU WHY.  It's because I'm a bad trader and I KNOW I'M A BAD TRADER.  Yeah you good traders can spot the highs and the lows pit pat piffy wing wong wang just like that and make a millino bucks sure no problem bro.  Likewise the weak hands are like OH NO IT'S GOING DOWN I'M GONNA SELL he he he and then they're like OH GOD MY ASSHOLE when the SMART traders who KNOW WHAT THE FUCK THEY'RE DOING buy back in but you know what?  I'm not part of that group.  When the traders buy back in I'm already part of the market capital so GUESS WHO YOU'RE CHEATING day traders NOT ME~!  Those taunt threads saying "OHH YOU SHOULD HAVE SOLD" YEAH NO SHIT.  NO SHIT I SHOULD HAVE SOLD.  I SHOULD HAVE SOLD MOMENTS BEFORE EVERY SELL AND BOUGHT MOMENTS BEFORE EVERY BUY BUT YOU KNOW WHAT NOT EVERYBODY IS AS COOL AS YOU.  You only sell in a bear market if you are a good day trader or an illusioned noob.  The people inbetween hold.  In a zero-sum game such as this, traders can only take your money if you sell."
Tags = ["history", "hodl", "bitcointalk"]

[The three economic eras of Bitcoin]
Link = ["https://medium.com/@rusty_lightning/the-three-economic-eras-of-bitcoin-d43bf0cf058a"]
Description = "The way the bitcoin ecosystem will play out is written in the mathematics of its consensus rules; we should all know the three phases it will go through."]
Tags = ["bitcoin", "history", "economics"]

[@dantwany on internet payments history]
Link = ["https://twitter.com/dantwany/status/939987392496365569", "http://web.archive.org/web/19961130160745/http://ganges.cs.tcd.ie:80/mepeirce/Project/oninternet.html"]
Description = "Bitcoin is sometimes compared Netscape and it's said some other will dethrone it. There have been many digital currency systems created that failed. Bitcoin is where it's today because it's a success. Payment mechanisms designed for the Internet (1996)"
Tags = ["bitcoin", "history", "digital-currency"]

[Before Babylon, Beyond Bitcoin: From Money That We Understand to Money That Understands Us (Perspectives)]
Link = ["https://the-eye.eu/public/concen.org/Before%20Babylon%2C%20Beyond%20Bitcoin%20%282017%29%20%28Pdf%29%20Gooner/Before%20Babylon%2C%20Beyond%20Bitcoin%20%282017%29.pdf"
Description = "Dave Birch looks back over the history of money, spanning thousands of years. He sees in the past, both recent and ancient, evidence for several possible futures. Looking further back to a world before cash and central banks, there were multiple ‘currencies' operating at the level of communities, and the use of barter for transactions. Perhaps technology will take us back to the future, a future that began back in 1971, when money became a claim backed by reputation rather than by physical commodities of any kind. Since then, money has been bits. The author shows that these phenomena are not only possible in the future, but already upon us."
Tags = ["history", "bitcoin", "books"]

[crypto— how the code rebels beat the government— saving privacy in the digital age]
Link = ["http://www.academia.edu/4903458/Crypto_-_How_the_Code_Rebels_Beat_the_Government_-_Saving_Privacy_in_the_Digital_Age"
Description = "The backbone of Crypto is a series of interviews conductedover the past decade withthe people who populate, or have had animpact on, the world of cryptography."
Tags = ["history", "bitcoin", "books"]

[The Code Book: The Science of Secrecy from Ancient Egypt to Quantum Cryptography]
Link = ["https://www.amazon.com/Code-Book-Science-Secrecy-Cryptography/dp/0385495323"]
Description = "Simon Singh offers the first sweeping history of encryption, tracing its evolution and revealing the dramatic effects codes have had on wars, nations, and individual lives. From Mary, Queen of Scots, trapped by her own code, to the Navajo Code Talkers who helped the Allies win World War II, to the incredible (and incredibly simple) logisitical breakthrough that made Internet commerce secure, The Code Book tells the story of the most powerful intellectual weapon ever known: secrecy."
Tags = ["history", "cryptography", "books"]

[Digital Gold: Bitcoin and the Inside Story of the Misfits and Millionaires Trying to Reinvent Money]
Link = ["https://www.harpercollins.com/9780062572066/digital-gold/"]
Description = "Bitcoin, the landmark digital money and financial technology, has spawned a global social movement with utopian ambitions. The notion of a new currency, maintained by the computers of users around the world, has been the butt of many jokes, but that has not stopped it from growing into a technology worth billions of dollars, supported by the hordes of followers who have come to view it as the most important new idea since the creation of the Internet."
Tags = ["bitcoin", "history", "digital-currency", "books"]

[@francispouliot Looking back on UASF]
Link = ["https://twitter.com/francispouliot_/status/1037379672282152960", "https://twitter.com/francispouliot_/status/1037358649029668864"]
Description = "1/ Full text of the article: "After the one year anniversary of Bitcoin’s iconic User Activated Soft Fork, we had the pleasure of speaking with Francis Pouliot, CEO of Bylls, a major proponent in the campaign to keep Bitcoin under its users’ control."
Tags = ["bitcoin", "history", "uasf"]

[Bitcoin is not Dead]
Link = ["https://www.forbes.com/sites/michaeldelcastillo/2018/09/06/bitcoin-is-not-dead/#355f465b5bdd"]
Description = "The first recorded claim of bitcoin’s demise was in 2010, on a little-known blog that found itself posted on a record of “bitcoin obituaries” collected by 99Bitcoins, a bitcoin information site. While I consider myself among the first wave of bitcoin writers, having written my first article on the subject in 2011, this early claim of bitcoin’s death came when the cryptocurrency was valued at only $0.23. It is now worth almost $7,000."
Tags = ["bitcoin", "history"]


https://www.bloomberg.com/view/articles/2018-09-18/bitcoin-stumble-shows-bitmain-a-ghost-of-crises-past?utm_medium=social&utm_source=twitter&utm_content=crypto&utm_campaign=socialflow-organic

---

https://twitter.com/varun_mathur/status/1038107664868208640

---

https://medium.com/tbis-weekly-bits/bitcoins-constitutional-crisis-why-i-support-the-uasf-5b0ab325d8b6

---

https://www.bloomberg.com/view/articles/2018-09-18/bitcoin-stumble-shows-bitmain-a-ghost-of-crises-past

---

https://twitter.com/scott_lew_is/status/1042043969348284417

---

https://stephanlivera.com/2018/09/20/slp23-economic-eras-of-bitcoin-and-lightning-development-with-rusty-russell-of-blockstream/

---

https://twitter.com/notgrubles/status/1043569394901602304

---

https://youtu.be/cagoyF3WePo

---

https://twitter.com/BitcoinErrorLog/status/1044207811603943425

---

https://steemit.com/crypto/@sxiii/oldest-icos

---

https://www.youtube.com/watch?v=EkeCapBOQQ0

---

https://oxt.me/history

---

https://www.bitcoin.kn/legendary/

---

https://www.theinvestorspodcast.com/blog/debt-deflation-italian-style/

---

http://archive.is/H8UGk

---

https://www.wired.com/2016/06/the-uncanny-mind-that-built-ethereum/

---

https://unblock.net/nick-szabo/

---

https://blockchainlibrary.org/category/reading-lists/bitcoin-history/

---

https://www.wsj.com/articles/the-eureka-moment-that-made-bitcoin-possible-1527268025

---

https://nakamotoinstitute.org/trusted-third-parties/

---

https://ebrary.net/7927/education/brief_history_digital_currencies#360
