PeerCoin White Paper: https://peercoin.net/assets/paper/peercoin-paper.pdf - Arguably the first coin to introduce Proof of Stake as an alternative to Proof of Work for distributed consensus.

Dan Larimer introduces Delegated Proof of Stake (DPoS)
https://bravenewcoin.com/assets/Uploads/TransactionsAsProofOfStake10.pdf

BitShares: https://bitshares.org/technology/delegated-proof-of-stake-consensus/- First coin to use DPoS

Proof of Stake Thread: https://bitcointalk.org/index.php?topic=27787.0 Shows the original idea of PoS and its criticisms and benefits
infominer9/29/2018, 5:25:53 PM

Proof of Stake Velocity
-https://www.reddcoin.com/papers/PoSV.pdf(edited)

PoW, PoS, & Hybrid protocols: A Matter of Complexity?
-https://arxiv.org/pdf/1805.08674.pdf


https://steemit.com/dpos/@dantheman/dpos-consensus-algorithm-this-missing-white-paper


https://steemit.com/bitcoin/@funmemes/variations-of-proof-of-stake


http://forum.mymue.com/topic/80/mue-announces-its-move-to-proof-of-stake-pos


https://www.coindesk.com/the-creator-of-proof-of-stake-thinks-he-finally-figured-it-out


https://twitter.com/KyleSamani/status/1039822086808592384

(Formatted embeds are currently not supported)
infominer9/29/2018, 5:29:46 PM

https://medium.com/@laurentmt/electric-money-e2cd34f78f56


https://download.wpsoftware.net/bitcoin/pos.pdf


https://medium.com/@venkinarayanan/block-chain-mining-proof-work-stake-95345d8af443


https://medium.com/@hugonguyen/proof-of-stake-the-wrong-engineering-mindset-15e641ab65a2


https://medium.com/@hugonguyen/proof-of-stake-private-keys-attacks-and-unforgeable-costliness-the-unsung-hero-5caca70b01cb


https://pdfs.semanticscholar.org/d873/a75502e45e1791cd6fc8d1ce670e1337063a.pdf


Blockchain Without Waste: Proof-of-Stake


https://ethresear.ch/t/formal-barriers-to-longest-chain-proof-of-stake-protocols/3509


https://cyber.stanford.edu/sites/default/files/formal_barriers_to_proof-of-stake_protocols.pdf


http://www.truthcoin.info/blog/pos-still-pointless/


https://twitter.com/eric_lombrozo/status/1045916707821408256

(Formatted embeds are currently not supported)
