https://concourseq.io/catalog/7731
infominer8/8/2018, 12:54:20 AM

https://www.tokendaily.co/blog/the-best-fundamental-indicator-new-inflows
infominer8/8/2018, 1:06:40 AM

https://medium.com/@jbackus/invest-in-the-ugly-duckling-decentralization-product-market-fit-and-the-law-bea856a6bbad
infominer8/10/2018, 7:32:44 PM

https://concourseq.io
infominer8/12/2018, 10:20:30 PM

https://steemit.com/cryptocurrency/@neoxian/neoxian-s-guide-to-evaluating-a-crypto-currency
infominer8/12/2018, 10:29:20 PM

https://www.reddit.com/r/CryptoCurrency/comments/7psz41/whats_in_a_whitepaper_a_detailed_analysis_of_what/
https://cryptopotato.com/10-keys-evaluating-initial-coin-offering-ico-investments/
https://hackernoon.com/evaluating-tokens-and-icos-e6c22c1885bb
infominer8/12/2018, 10:30:26 PM

https://hackernoon.com/a-framework-for-evaluating-cryptocurrencies-e1b504179848
infominer8/12/2018, 10:30:54 PM(edited)

https://cryptoear.com/ -keeps track of twitter mentions
infominer8/12/2018, 10:31:48 PM

https://jordancooper.blog/2017/05/23/what-i-look-for-in-cryptocoins/
https://thecontrol.co/our-process-for-evaluating-new-tokens-4627ed97f500
infominer8/12/2018, 10:33:42 PM

https://twitter.com/paulsbohm/status/1015027146157273088

(Formatted embeds are currently not supported)
infominer8/12/2018, 10:33:57 PM

https://bravenewcoin.com/news/is-tracking-github-activity-a-good-way-to-evaluate-crypto-projects/
infominer8/12/2018, 10:55:13 PM

https://blockgeeks.com/guides/why-most-icos-will-fail/
infominer8/12/2018, 10:55:25 PM

https://hackernoon.com/4-primary-reasons-why-icos-fail-43274fd34e2e
infominer8/12/2018, 10:55:37 PM

https://coincentral.com/why-are-so-many-icos-failing/
infominer8/12/2018, 10:55:52 PM

https://modernconsensus.com/people/innovators/why-most-icos-will-fail-monetago/
infominer8/12/2018, 10:56:05 PM

https://nulltx.com/why-do-so-many-icos-fail-heres-what-the-experts-say/
infominer8/12/2018, 10:56:17 PM

https://captainaltcoin.com/why-most-icos-fail/
infominer8/12/2018, 10:56:27 PM

https://thechain.media/reasons-why-most-icos-fail
infominer8/12/2018, 10:56:40 PM

https://steemit.com/ico/@coinhoarder/most-icos-will-fail
infominer8/12/2018, 10:56:55 PM

https://medium.com/iconominet/why-icos-fail-1f9530a6d135
infominer8/12/2018, 10:57:02 PM

https://medium.com/iconominet/ico-2-0-what-is-the-ideal-ico-ee9d285a8939#.btpvwin8c
infominer8/12/2018, 10:57:31 PM

https://cryptovest.com/education/5-reasons-your-ico-will-fail-and-how-to-save-it/
infominer8/13/2018, 2:45:31 PM

https://medium.com/@michaelflaxman/icos-are-cancer-c404594f181b
infominer8/13/2018, 2:45:39 PM

https://medium.com/@avtarsehra/icos-and-economics-of-lemon-markets-96638e86b3b2
infominer8/13/2018, 2:45:53 PM

https://hackernoon.com/most-icos-fail-tale-of-two-worlds-d1ab7625ff66
infominer8/13/2018, 2:46:07 PM

https://news.bitcoin.com/46-last-years-icos-failed-already/
infominer8/13/2018, 2:46:24 PM

https://hackernoon.com/stay-away-from-icos-which-34ac544e1d49
infominer8/13/2018, 2:46:34 PM

https://medium.com/blockchannel/understanding-the-ethereum-ico-token-hype-429481278f45
infominer8/13/2018, 2:46:43 PM

https://medium.com/@cincinnati/the-ponzico-white-paper-8baa98b19b97
infominer8/18/2018, 6:28:42 PM

https://twitter.com/NTmoney/status/958381086718902277

(Formatted embeds are currently not supported)
infominer8/20/2018, 3:24:54 PM

https://twitter.com/SarahJamieLewis/status/1010731016456003584

(Formatted embeds are currently not supported)
infominer8/25/2018, 10:03:43 PM

https://twitter.com/ReformedBroker/status/1017748548207685632

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:11:42 AM

https://hackernoon.com/valuing-productive-cryptoassets-89cedad444e6
infominer8/28/2018, 3:14:19 PM

https://t.co/sgMOn40ZOt
infominer9/7/2018, 2:39:21 AM

https://twitter.com/DoveyWan/status/1035729838261264384

(Formatted embeds are currently not supported)
infominer9/17/2018, 12:13:20 AM

https://twitter.com/adamludwin/status/888168591043969024

(Formatted embeds are currently not supported)
infominer9/22/2018, 9:48:29 PM

https://twitter.com/Melt_Dem/status/1038173464291680256

(Formatted embeds are currently not supported)
infominer9/23/2018, 1:00:29 AM

https://medium.com/@nlw/complexity-theater-3375a4bdafba
infominer9/28/2018, 12:26:10 AM

https://medium.com/@visionhill_/introducing-a-crypto-benchmark-framework-a873a54a7cfd
infominer9/28/2018, 7:01:04 PM

https://twitter.com/danzuller/status/1042854743880724481
