infominer10/15/2018, 9:49:37 PM

https://www.linkedin.com/pulse/best-python-librariespackages-finance-financial-data-majid-aliakbar/
infominer10/15/2018, 9:55:15 PM

https://www.datacamp.com/community/tutorials/finance-python-trading
infominer10/15/2018, 10:00:11 PM

https://medium.com/@ashishsingal1/introducing-betalyzer-a-fintech-tutorial-110ac9abda58
infominer10/15/2018, 10:29:05 PM

http://www.tradingwithpython.com/?page_id=439
infominer10/15/2018, 10:31:10 PM

https://www.quantstart.com/articles/Quant-Reading-List-Python-Programming
infominer10/15/2018, 11:55:43 PM

https://www.reddit.com/r/investing/comments/90gzh6/learning_both_financial_modelling_and_python/
infominer10/21/2018, 1:36:17 PM

https://itunes.apple.com/us/podcast/chat-traders-conversations-talented-traders-in-stocks/id957265404?mt=2&i=1000420535357
infominer10/21/2018, 2:05:00 PM

https://chatwithtraders.com/ep-166-hugo-bowne-anderson/
infominer10/21/2018, 2:05:16 PM

https://github.com/infominer33/Crypto-library/blob/master/library/Python%20for%20finace.html
infominer10/26/2018, 1:11:45 PM

http://lambda-the-ultimate.org/node/2852
