infominer8/22/2018, 11:42:50 PM

https://twitter.com/NickSzabo4/status/1031231342803972096

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:25:58 AM

https://twitter.com/GoldTelegraph_/status/991791693199425536

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:27:16 AM

https://twitter.com/MI_Investments/status/1028468590356250624

(Formatted embeds are currently not supported)
infominer8/30/2018, 7:16:02 PM

https://twitter.com/spectatorindex/status/1028362918142730240

(Formatted embeds are currently not supported)
infominer8/30/2018, 7:30:39 PM

https://twitter.com/cburniske/status/1033828237347106822

(Formatted embeds are currently not supported)
infominer8/30/2018, 7:37:53 PM

https://www.theinstitutionalriskanalyst.com/single-post/2018/06/09/Update-The-Financial-Repression-Index
infominer8/30/2018, 8:20:14 PM

https://twitter.com/BobMurphyEcon/status/1035314165932548097

(Formatted embeds are currently not supported)
infominer9/4/2018, 12:53:36 AM

https://cloud.coinfeed.com/share/post/105382915356750/641535675077/25481
infominer9/4/2018, 11:48:34 AM

http://archive.is/Cezf0
infominer9/8/2018, 8:19:14 PM

https://mises.org/library/origins-federal-reserve
infominer9/8/2018, 8:26:36 PM

https://www.youtube.com/watch?v=WVxWPkMXOmw
infominer9/8/2018, 8:27:52 PM

https://www.youtube.com/watch?v=2nBPN-MKefA
infominer9/17/2018, 12:56:44 PM

https://www.stitcher.com/podcast/the-bitcoin-game/e/54505040
infominer9/17/2018, 12:59:06 PM(edited)

good discussion about how international transactions work and how banks hold our money.
infominer9/22/2018, 9:53:27 PM

https://twitter.com/GratkeWealth/status/1037710142857342976

(Formatted embeds are currently not supported)
infominer9/22/2018, 9:53:41 PM

https://twitter.com/LanceRoberts/status/1037706007869353984

(Formatted embeds are currently not supported)
infominer9/22/2018, 10:01:25 PM

https://twitter.com/wsculley/status/1038549218686902273

(Formatted embeds are currently not supported)
infominer9/22/2018, 10:04:32 PM

https://mises.org/library/what-has-government-done-our-money
infominer9/23/2018, 5:52:49 AM

https://twitter.com/hugohanoi/status/973693594128211968

(Formatted embeds are currently not supported)
infominer9/27/2018, 11:27:23 PM

https://coingape.com/bitcoin-2020-set-for-next-financial-crisis/
infominer9/28/2018, 12:23:07 AM

https://youtu.be/PHe0bXAIuk0
infominer9/28/2018, 11:29:27 PM

https://letstalkbitcoin.com/blog/post/what-bitcoin-did-36-an-interview-with-caitlin-long-saifedean-ammous
infominer10/5/2018, 7:31:04 AM

https://medium.com/@brucefenton/how-do-you-know-you-own-your-stocks-you-dont-so-who-has-the-ledger-262def52ae4
infominer10/5/2018, 3:58:30 PM

https://twitter.com/intjr/status/1048098080388603905

(Formatted embeds are currently not supported)
