[""]
Link = ["https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3198694"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@romanornr/bitmex-perpetual-swap-2d125a304dd
Description = ""
Tags = ["",""]

[""]
Link = ["https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3111467
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@alexrachnog/ai-for-algorithmic-trading-7-mistakes-that-could-make-me-broke-a41f94048b8c
Description = ""
Tags = ["",""]

[""]
Link = ["https://docs.google.com/document/d/15c3rN15rkXldY8Te3GDG4NG7noaaoikydOoZQlElwXw/edit?usp=drivesdk
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.psychologytoday.com/us/blog/mind-in-the-machine/201712/how-fear-is-being-used-manipulate-cryptocurrency-markets
Description = ""
Tags = ["",""]

[""]
Link = ["https://bitfalls.com/2018/01/12/anatomy-pump-dump-group/
Description = ""
Tags = ["",""]

[""]
@TradersLibrary  TraderLibrary to enter, click on the following link: 👇
Link = ["https://telegram.me/joinchat/AAppPT3cOnM48-Kqbm7FGg
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.babypips.com/
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/cryptocurrency/@wolfofpoloniex/bare-basics-of-trading-cryptocurrency
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/cryptocurrency/@connecteconomy/the-biggest-regret-of-new-crypto-traders
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/@twoblokestrading/elliott-wave-principle-key-to-market-behaviour-book-review
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/bitcoin/@yarr/how-to-use-moving-averages-to-day-trade-on-alts-on-binance
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/crypto/@cryptobroye/manipulation-vital-information-on-market-movement-and-how-to-read-their-efforts-for-usdprofit
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/cryptotrading/@cryptobroye/success-strategies-trading-crypto-s-equities-with-triangle-chart-patterns
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/bitcoin/@cryptobroye/success-strategies-2-elaboration-on-trading-triangles-trading-strategy
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/cryptocurrencies/@cryptobroye/stop-loss-hunting-whale-manipulation-strategies-2
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/bitcoin/@cryptobroye/success-strategies-3-price-action-trading-inside-bar-engulfing-bar-chart-patterns
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/bitcoin/@cryptobroye/success-strategies-4-trading-fibonacci-retrace-and-expansion-to-pinpoint-entries-and-exits
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/bitcoin/@cryptobroye/success-strategies-5-recognising-and-tradin-support-and-resistance-levels
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/bitcoin/@cryptobroye/success-strategies-6-the-pyramid-trade-management-strategy
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@Cryptilicious/risk-management-for-trading-8608d813872d
Description = ""
Tags = ["",""]

[""]
Link = ["https://techburst.io/some-basics-on-trading-crypto-fb74572ca9de
Description = ""
Tags = ["",""]

[""]
Link = ["https://blog.goodaudience.com/answering-all-cryptocurrency-newbie-questions-d1683652dec8
Description = ""
Tags = ["",""]

[""]
http://www.profitf.com/articles/patterns/abcd-pattern-trading/
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@WarriorTrading/ichimoku-cloud-definition-day-trading-terminology-7b34e98d2ea2
Description = ""
Tags = ["",""]

[""]
http://thepatternsite.com/index.html
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.bollingerbands.com/
Description = ""
Tags = ["",""]

[""]
http://www.libertylifetrail.com/education/learntrading
Description = ""
Tags = ["",""]

[""]
http://www.stockcharts.com/
Description = ""
Tags = ["",""]

[""]
Link = ["https://coinmonsta.io/metrics
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.tradingview.com
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.investopedia.com
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@cryptocreddy/5-useful-tradingview-tricks-30404ed41653
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@cryptol0gy/the-road-to-becoming-a-shark-in-the-crypto-markets-part-1-230675138f29
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@cryptol0gy/conquer-professional-cryptocurrency-trading-with-this-unique-easy-free-guide-part-2-946a301ac8da
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@cryptomeds/best-rsi-guide-for-cryptocurrency-youll-ever-find-d707e81d2a96
Description = ""
Tags = ["",""]

[""]
http://www.chart-formations.com/indicators/divergence.aspx
Description = ""
Tags = ["",""]

[""]
Link = ["https://theicojournal.com/trading-versus-managing-your-crypto-portfolio-a-lesson-in-oxymorons/
Description = ""
Tags = ["",""]

[""]
Link = ["https://steemit.com/cryptocurrency-bitcoin/@whalereports/cryptocurrencytrading9guidelinestomakebankandavoidgettingrekt-67r0rwjmlv
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.turtlebc.com/tools/buy_percentage
Description = ""
Tags = ["",""]

[""]
Link = ["https://whalereports.com/yarrs-beginners-guide-how-to-use-moving-averages-to-day-trade/
Description = ""
Tags = ["",""]

[""]
Link = ["https://pbs.twimg.com/media/BuCYjreIEAAdZhv.jpg
Description = ""
Tags = ["",""]

(image attachment not found)

(Formatted embeds are currently not supported)

[""]
Link = ["https://twitter.com/CryptoChoe/status/1012031916160233472
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1012453593876660224?s=19

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@homeytel
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/YORKyor780/status/1027757318522523648
Description = ""
Tags = ["",""]

[""]

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/AriDavidPaul/status/1030164882694578176

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/RyanSAdams/status/1029406662082396160

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/HsakaTrades/status/1030321802403373057

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
^^^ solid thread
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/TheCryptoDog/status/1030564719495503872

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/ThinkingUSD/status/1030642377067704320

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://library.cryptotradercentral.com/
Description = ""
Tags = ["",""]

[""]
-Trading Books
Link = ["https://drive.google.com/drive/folders/1Q6uznnEm7yDT9RrqKkF2_uXdfKttxA_M
Description = ""
Tags = ["",""]

[""]
Link = ["https://drive.google.com/open?id=0B9b4K-iw1yCoZmVobm8wcHNIS2s
Description = ""
Tags = ["",""]

[""]
Link = ["https://drive.google.com/open?id=1XM60dHQF9Ii9SGEkk59k2Vou5qYKVK7T
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/YORKyor780/status/1030728400254775296
Description = ""
Tags = ["",""]

[""]

(Formatted embeds are currently not supported)
^^^ thread
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/cryptinfominer/status/1031620646659403776?s=19

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1031883507390459905
Description = ""
Tags = ["",""]

[""]
(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1032329625815457799

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/EthereumNetw/status/1032343650469076993

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://cdn.discordapp.com/attachments/354298918768738305/481961081443581963/wyckoffdistribution1.png
(image attachment not found)
Description = ""
Tags = ["",""]

[""]
Link = ["https://cdn.discordapp.com/attachments/354298918768738305/481961301661188096/AWTC-WyckoffPhases.png
(image attachment not found)
Description = ""
Tags = ["",""]

[""]
good alternative to cmc - 
Link = ["https://onchainfx.com/
multi blockchain explorer - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://chainz.cryptoid.info/
more visual global charts - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://coinlib.io/global-crypto-charts
orderbook heatmap - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://tensorcharts.com/
simple sentiment analysis - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://alternative.me/crypto/fear-and-greed-index/
bitmex margin information - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://coinfarm.online/index_en.asp
additional margin data - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://datamish.com/d/000000004/btcusd?refresh=20s&orgId=1
charting + info of any coins on cmc - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://bitscreener.com/
buy market % + other indicator signals - 
Description = ""
Tags = ["",""]

[""]
http://www.cryptowho.de/
github activity tracker - 
Description = ""
Tags = ["",""]

[""]
Link = ["https://cryptomiso.com/
Description = ""
Tags = ["",""]

[""]
Link = ["https://library.cryptotradercentral.com/
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/brian_armstrong/status/1009192006512328704

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/cryptinfominer/status/1021871857832742913

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/AltcoinPsycho/status/1021928481200824322

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/nebraskangooner/status/1024463540181258240

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/Wolf__Daddy/status/1012258460673683461

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoSays/status/1026287741045272576

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/YORKyor780/status/1026488058512896001

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://babypips.com
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/ThinkingUSD/status/1030642377067704320

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/MoonOverlord/status/1031004700676710400

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/KunalDaSen/status/1029016530640625664

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1032329625815457799

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1033796583333289986

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/ercwl/status/1033816350958014469

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
http://gann.su/book/eng/
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.venturecoinist.com/bot
Description = ""
Tags = ["",""]

[""]
"The Coinist Bot is an automated strategy analyzing Bitcoin and other large cap alts."
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CarpeNoctom/status/1034889451137376257

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1035223770267611136

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/pierre_rochard/status/1035635907498532865

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/MoonOverlord/status/1009912924822016002

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://pca.st/P5sC
Description = ""
Tags = ["",""]

[""]
Link = ["https://cdn.discordapp.com/attachments/350717439388024835/350728664322932746/microbtc-bittrex.jpg
(image attachment not found)
Description = ""
Tags = ["",""]

[""]
Link = ["https://media.discordapp.net/attachments/350717439388024835/362750300513107978/unknown_2.png
(image attachment not found)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/Beastlyorion/status/1035972119472099329

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/FedKassad/status/1035627093084827648

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/VentureCoinist/status/1034570394190135298

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
http://www.r-5.org/files/books/trading/schoolbooks/Douglas_E_Zalesky-The_25-point_Mantra-EN.pdf
vincent9/10/2018, 10:45:26 AM

Description = ""
Tags = ["",""]

[""]
Link = ["https://sierrachart.com
trading platform with lots of features, like footprint charts, heatmaps and all that  . has poloniex, bitmex, bitfinex and okcoin currently
Description = ""
Tags = ["",""]

[""]
lots of good articles especially on the psychology http://yourtradingcoach.com/site-map/
Description = ""
Tags = ["",""]

[""]
obligatory watching 
Link = ["https://www.youtube.com/channel/UCT43ffXmotx7i903Yxcwxjw/videos
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1036714196027801600

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://youtu.be/YVz5zfiBQjM
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/Lucid_TA/status/1037510808782032896

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1037772897241255936

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/alistairmilne/status/1037793389629108224

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://bitcoinist.com/cnbc-reverse-bitcoin-price-impress/
Description = ""
Tags = ["",""]

[""]
Link = ["https://pbs.twimg.com/media/DmoTJNlXcAAPQza.jpg:large
(image attachment not found)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/BTCDJS/status/1038714265392173056

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/PeterLBrandt/status/1039575413985398784

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/StockmarketJedi/status/1039635130409615361

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoCred/status/1040700546221584384

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/trader_travis/status/1040752102853599234

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoHornHairs/status/1041112269927505921

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/blocktoken/how-traders-use-cryptocurrency-arbitrage-to-make-profits-8e5f3adb75c4
Description = ""
Tags = ["",""]

[""]
http://www.technical-analysis.com/learnTA/RSINotOBOS/RSINotOBOS.html
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/tradingroomapp/status/1040868470953410560

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/CryptoQF/status/1042265797584797696

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://news.bitcoin.com/six-new-and-improved-cryptocurrency-analysis-tools/
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@cryptocreddy/does-technical-analysis-work-fa90413a8328
Description = ""
Tags = ["",""]

[""]
plenty of trading books Link = ["https://t.me/LibTA
Description = ""
Tags = ["",""]

[""]
Link = ["https://github.com/hientm36/gnidart
Description = ""
Tags = ["",""]

[""]
Link = ["https://twitter.com/JimAllmendinger/status/1044710492923617281

(Formatted embeds are currently not supported)
Description = ""
Tags = ["",""]

[""]
Link = ["https://tensorcharts.com/
Description = ""
Tags = ["",""]

[""]
Link = ["https://aggr.trade/#
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.marketvolume.com/technicalanalysis/rating.asp
Description = ""
Tags = ["",""]

[""]
Link = ["https://cryptowest.com/books-trading-tools/
Description = ""
Tags = ["",""]

[""]
Link = ["https://cryptowest.com/2018/08/24/one-important-concepts-trading/
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.youtube.com/watch?v=Ou_BPr84GHY
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@ThinkingUSD/deribit-bitcoin-options-and-volatility-b370ba276761
Description = ""
Tags = ["",""]

[""]
Link = ["https://drive.google.com/file/d/1Ew_O4fMdGM2M8NhYDFB0NJmLMCIQi-Tl/view
Description = ""
Tags = ["",""]

[""]
Link = ["https://app.compound.finance/
Description = ""
Tags = ["",""]

[""]
Link = ["https://avc.com/2018/10/fully-diluted-market-value/
Description = ""
Tags = ["",""]

[""]
Link = ["https://medium.com/@cryptocreddy/comprehensive-guide-to-position-size-and-leverage-2e27764ce9e0
Description = ""
Tags = ["",""]

[""]
that's the shape of about to moon
(image attachment not found)
