, 12:00:41 AM

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3198694
infominer8/8/2018, 12:10:53 AM

https://medium.com/@romanornr/bitmex-perpetual-swap-2d125a304dd
infominer8/8/2018, 12:29:11 AM

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3111467
infominer8/8/2018, 9:25:31 PM

https://medium.com/@alexrachnog/ai-for-algorithmic-trading-7-mistakes-that-could-make-me-broke-a41f94048b8c
infominer8/10/2018, 4:52:50 PM

https://docs.google.com/document/d/15c3rN15rkXldY8Te3GDG4NG7noaaoikydOoZQlElwXw/edit?usp=drivesdk
infominer8/10/2018, 7:13:58 PM

https://www.psychologytoday.com/us/blog/mind-in-the-machine/201712/how-fear-is-being-used-manipulate-cryptocurrency-markets
infominer8/10/2018, 8:04:19 PM

https://bitfalls.com/2018/01/12/anatomy-pump-dump-group/
infominer8/12/2018, 2:15:42 PM

@TradersLibrary  TraderLibrary to enter, click on the following link: 👇
https://telegram.me/joinchat/AAppPT3cOnM48-Kqbm7FGg
infominer8/12/2018, 10:13:29 PM

https://www.babypips.com/
infominer8/12/2018, 10:20:43 PM

https://steemit.com/cryptocurrency/@wolfofpoloniex/bare-basics-of-trading-cryptocurrency
infominer8/12/2018, 10:20:53 PM

https://steemit.com/cryptocurrency/@connecteconomy/the-biggest-regret-of-new-crypto-traders
infominer8/12/2018, 10:21:04 PM

https://steemit.com/@twoblokestrading/elliott-wave-principle-key-to-market-behaviour-book-review
infominer8/12/2018, 10:21:12 PM

https://steemit.com/bitcoin/@yarr/how-to-use-moving-averages-to-day-trade-on-alts-on-binance
infominer8/12/2018, 10:21:25 PM

https://steemit.com/crypto/@cryptobroye/manipulation-vital-information-on-market-movement-and-how-to-read-their-efforts-for-usdprofit
infominer8/12/2018, 10:21:40 PM

https://steemit.com/cryptotrading/@cryptobroye/success-strategies-trading-crypto-s-equities-with-triangle-chart-patterns
infominer8/12/2018, 10:21:53 PM

https://steemit.com/bitcoin/@cryptobroye/success-strategies-2-elaboration-on-trading-triangles-trading-strategy
infominer8/12/2018, 10:22:08 PM

https://steemit.com/cryptocurrencies/@cryptobroye/stop-loss-hunting-whale-manipulation-strategies-2
infominer8/12/2018, 10:22:18 PM

https://steemit.com/bitcoin/@cryptobroye/success-strategies-3-price-action-trading-inside-bar-engulfing-bar-chart-patterns
infominer8/12/2018, 10:22:26 PM

https://steemit.com/bitcoin/@cryptobroye/success-strategies-4-trading-fibonacci-retrace-and-expansion-to-pinpoint-entries-and-exits
infominer8/12/2018, 10:22:34 PM

https://steemit.com/bitcoin/@cryptobroye/success-strategies-5-recognising-and-tradin-support-and-resistance-levels
infominer8/12/2018, 10:22:40 PM

https://steemit.com/bitcoin/@cryptobroye/success-strategies-6-the-pyramid-trade-management-strategy
infominer8/12/2018, 10:26:06 PM(edited)

https://medium.com/@Cryptilicious/risk-management-for-trading-8608d813872d
https://techburst.io/some-basics-on-trading-crypto-fb74572ca9de
https://blog.goodaudience.com/answering-all-cryptocurrency-newbie-questions-d1683652dec8
http://www.profitf.com/articles/patterns/abcd-pattern-trading/
https://medium.com/@WarriorTrading/ichimoku-cloud-definition-day-trading-terminology-7b34e98d2ea2
http://thepatternsite.com/index.html
https://www.bollingerbands.com/
http://www.libertylifetrail.com/education/learntrading
http://www.stockcharts.com/
https://coinmonsta.io/metrics
https://www.tradingview.com
https://www.investopedia.com
infominer8/12/2018, 10:28:52 PM

https://medium.com/@cryptocreddy/5-useful-tradingview-tricks-30404ed41653
https://medium.com/@cryptol0gy/the-road-to-becoming-a-shark-in-the-crypto-markets-part-1-230675138f29
https://medium.com/@cryptol0gy/conquer-professional-cryptocurrency-trading-with-this-unique-easy-free-guide-part-2-946a301ac8da
https://medium.com/@cryptomeds/best-rsi-guide-for-cryptocurrency-youll-ever-find-d707e81d2a96
http://www.chart-formations.com/indicators/divergence.aspx
infominer8/12/2018, 10:29:37 PM

https://theicojournal.com/trading-versus-managing-your-crypto-portfolio-a-lesson-in-oxymorons/
infominer8/12/2018, 10:30:08 PM

https://steemit.com/cryptocurrency-bitcoin/@whalereports/cryptocurrencytrading9guidelinestomakebankandavoidgettingrekt-67r0rwjmlv
https://www.turtlebc.com/tools/buy_percentage
https://whalereports.com/yarrs-beginners-guide-how-to-use-moving-averages-to-day-trade/
infominer8/12/2018, 10:32:18 PM

https://pbs.twimg.com/media/BuCYjreIEAAdZhv.jpg
(image attachment not found)
infominer8/12/2018, 10:32:44 PM

https://twitter.com/CryptoChoe/status/1012031916160233472

(Formatted embeds are currently not supported)
infominer8/12/2018, 10:32:53 PM

https://twitter.com/CryptoCred/status/1012453593876660224?s=19

(Formatted embeds are currently not supported)
infominer8/12/2018, 10:33:03 PM

https://medium.com/@homeytel
infominer8/12/2018, 11:07:00 PM

https://twitter.com/YORKyor780/status/1027757318522523648

(Formatted embeds are currently not supported)
infominer8/16/2018, 4:43:47 PM

https://twitter.com/AriDavidPaul/status/1030164882694578176

(Formatted embeds are currently not supported)
infominer8/16/2018, 6:02:13 PM

https://twitter.com/RyanSAdams/status/1029406662082396160

(Formatted embeds are currently not supported)
infominer8/17/2018, 3:47:38 AM

https://twitter.com/HsakaTrades/status/1030321802403373057

(Formatted embeds are currently not supported)
infominer8/17/2018, 3:48:21 AM

^^^ solid thread
infominer8/17/2018, 6:10:19 PM

https://twitter.com/TheCryptoDog/status/1030564719495503872

(Formatted embeds are currently not supported)
infominer8/17/2018, 10:55:53 PM

https://twitter.com/ThinkingUSD/status/1030642377067704320

(Formatted embeds are currently not supported)
infominer8/18/2018, 12:14:41 AM

https://library.cryptotradercentral.com/
infominer8/18/2018, 12:16:15 AM

-Trading Books
https://drive.google.com/drive/folders/1Q6uznnEm7yDT9RrqKkF2_uXdfKttxA_M
infominer8/18/2018, 12:18:50 AM

https://drive.google.com/open?id=0B9b4K-iw1yCoZmVobm8wcHNIS2s
https://drive.google.com/open?id=1XM60dHQF9Ii9SGEkk59k2Vou5qYKVK7T
infominer8/18/2018, 4:31:09 AM

https://twitter.com/YORKyor780/status/1030728400254775296

(Formatted embeds are currently not supported)
infominer8/18/2018, 4:31:17 AM

^^^ thread
infominer8/20/2018, 3:25:26 PM

https://twitter.com/cryptinfominer/status/1031620646659403776?s=19

(Formatted embeds are currently not supported)
infominer8/23/2018, 12:01:59 AM

https://twitter.com/CryptoCred/status/1031883507390459905

(Formatted embeds are currently not supported)
infominer8/23/2018, 12:02:08 AM

https://twitter.com/CryptoCred/status/1032329625815457799

(Formatted embeds are currently not supported)
infominer8/23/2018, 12:02:55 AM

https://twitter.com/EthereumNetw/status/1032343650469076993

(Formatted embeds are currently not supported)
infominer8/23/2018, 2:18:49 PM

https://cdn.discordapp.com/attachments/354298918768738305/481961081443581963/wyckoffdistribution1.png
(image attachment not found)
infominer8/23/2018, 2:19:03 PM

https://cdn.discordapp.com/attachments/354298918768738305/481961301661188096/AWTC-WyckoffPhases.png
(image attachment not found)
infominer8/23/2018, 4:28:04 PM

good alternative to cmc - https://onchainfx.com/
multi blockchain explorer - https://chainz.cryptoid.info/
more visual global charts - https://coinlib.io/global-crypto-charts
orderbook heatmap - https://tensorcharts.com/
simple sentiment analysis - https://alternative.me/crypto/fear-and-greed-index/
bitmex margin information - https://coinfarm.online/index_en.asp
additional margin data - https://datamish.com/d/000000004/btcusd?refresh=20s&orgId=1
charting + info of any coins on cmc - https://bitscreener.com/
buy market % + other indicator signals - http://www.cryptowho.de/
github activity tracker - https://cryptomiso.com/
infominer8/25/2018, 9:29:32 PM

https://library.cryptotradercentral.com/
infominer8/25/2018, 9:48:57 PM

https://twitter.com/brian_armstrong/status/1009192006512328704

(Formatted embeds are currently not supported)
infominer8/25/2018, 10:20:37 PM

https://twitter.com/cryptinfominer/status/1021871857832742913

(Formatted embeds are currently not supported)
infominer8/25/2018, 10:21:39 PM

https://twitter.com/AltcoinPsycho/status/1021928481200824322

(Formatted embeds are currently not supported)
infominer8/25/2018, 10:48:44 PM

https://twitter.com/nebraskangooner/status/1024463540181258240

(Formatted embeds are currently not supported)
infominer8/25/2018, 10:53:32 PM

https://twitter.com/Wolf__Daddy/status/1012258460673683461

(Formatted embeds are currently not supported)
infominer8/25/2018, 11:58:10 PM

https://twitter.com/CryptoSays/status/1026287741045272576

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:06:43 AM

https://twitter.com/YORKyor780/status/1026488058512896001

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:27:47 AM(edited)

https://babypips.com
infominer8/26/2018, 12:44:46 AM

https://twitter.com/ThinkingUSD/status/1030642377067704320

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:50:30 AM

https://twitter.com/MoonOverlord/status/1031004700676710400

(Formatted embeds are currently not supported)
infominer8/26/2018, 12:52:02 AM

https://twitter.com/KunalDaSen/status/1029016530640625664

(Formatted embeds are currently not supported)
infominer8/28/2018, 3:12:41 PM

https://twitter.com/CryptoCred/status/1032329625815457799

(Formatted embeds are currently not supported)
infominer8/30/2018, 7:17:55 PM

https://twitter.com/CryptoCred/status/1033796583333289986

(Formatted embeds are currently not supported)
infominer8/30/2018, 7:27:04 PM

https://twitter.com/ercwl/status/1033816350958014469

(Formatted embeds are currently not supported)
infominer9/2/2018, 9:31:25 PM

http://gann.su/book/eng/
infominer9/3/2018, 9:59:13 PM

https://www.venturecoinist.com/bot
infominer9/3/2018, 9:59:47 PM

"The Coinist Bot is an automated strategy analyzing Bitcoin and other large cap alts."
infominer9/3/2018, 10:38:23 PM

https://twitter.com/CarpeNoctom/status/1034889451137376257

(Formatted embeds are currently not supported)
infominer9/4/2018, 12:31:37 AM

https://twitter.com/CryptoCred/status/1035223770267611136

(Formatted embeds are currently not supported)
infominer9/4/2018, 11:53:02 AM

https://twitter.com/pierre_rochard/status/1035635907498532865

(Formatted embeds are currently not supported)
infominer9/4/2018, 11:55:06 AM

https://twitter.com/MoonOverlord/status/1009912924822016002

(Formatted embeds are currently not supported)
infominer9/6/2018, 4:48:06 PM

https://pca.st/P5sC
infominer9/8/2018, 12:00:01 AM

https://cdn.discordapp.com/attachments/350717439388024835/350728664322932746/microbtc-bittrex.jpg
(image attachment not found)
infominer9/8/2018, 12:01:20 AM(edited)

https://media.discordapp.net/attachments/350717439388024835/362750300513107978/unknown_2.png
(image attachment not found)
infominer9/8/2018, 7:29:47 PM

https://twitter.com/Beastlyorion/status/1035972119472099329

(Formatted embeds are currently not supported)
infominer9/8/2018, 7:30:07 PM

https://twitter.com/FedKassad/status/1035627093084827648

(Formatted embeds are currently not supported)
infominer9/8/2018, 10:34:54 PM

https://twitter.com/VentureCoinist/status/1034570394190135298

(Formatted embeds are currently not supported)
infominer9/9/2018, 1:39:55 AM

http://www.r-5.org/files/books/trading/schoolbooks/Douglas_E_Zalesky-The_25-point_Mantra-EN.pdf
vincent9/10/2018, 10:45:26 AM

https://sierrachart.com
trading platform with lots of features, like footprint charts, heatmaps and all that  . has poloniex, bitmex, bitfinex and okcoin currently
vincent9/10/2018, 10:47:46 AM

lots of good articles especially on the psychology http://yourtradingcoach.com/site-map/
vincent9/10/2018, 10:55:29 AM

obligatory watching https://www.youtube.com/channel/UCT43ffXmotx7i903Yxcwxjw/videos
infominer9/13/2018, 9:10:46 AM

https://twitter.com/CryptoCred/status/1036714196027801600

(Formatted embeds are currently not supported)
infominer9/22/2018, 8:33:39 PM

https://youtu.be/YVz5zfiBQjM
infominer9/22/2018, 8:50:42 PM

https://twitter.com/Lucid_TA/status/1037510808782032896

(Formatted embeds are currently not supported)
infominer9/22/2018, 8:55:09 PM

https://twitter.com/CryptoCred/status/1037772897241255936

(Formatted embeds are currently not supported)
infominer9/22/2018, 8:59:04 PM

https://twitter.com/alistairmilne/status/1037793389629108224

(Formatted embeds are currently not supported)
infominer9/22/2018, 9:00:39 PM

https://bitcoinist.com/cnbc-reverse-bitcoin-price-impress/
infominer9/22/2018, 10:04:53 PM

https://pbs.twimg.com/media/DmoTJNlXcAAPQza.jpg:large
(image attachment not found)
infominer9/22/2018, 10:06:16 PM

https://twitter.com/BTCDJS/status/1038714265392173056

(Formatted embeds are currently not supported)
infominer9/23/2018, 12:56:41 AM

https://twitter.com/PeterLBrandt/status/1039575413985398784

(Formatted embeds are currently not supported)
infominer9/23/2018, 5:42:44 AM

https://twitter.com/StockmarketJedi/status/1039635130409615361

(Formatted embeds are currently not supported)
infominer9/23/2018, 5:58:11 AM

https://twitter.com/CryptoCred/status/1040700546221584384

(Formatted embeds are currently not supported)
infominer9/23/2018, 5:59:52 AM

https://twitter.com/trader_travis/status/1040752102853599234

(Formatted embeds are currently not supported)
infominer9/23/2018, 6:07:39 AM

https://twitter.com/CryptoHornHairs/status/1041112269927505921

(Formatted embeds are currently not supported)
infominer9/23/2018, 6:14:30 AM

https://medium.com/blocktoken/how-traders-use-cryptocurrency-arbitrage-to-make-profits-8e5f3adb75c4
vincent9/24/2018, 7:24:51 AM

http://www.technical-analysis.com/learnTA/RSINotOBOS/RSINotOBOS.html
infominer9/27/2018, 10:49:53 PM

https://twitter.com/tradingroomapp/status/1040868470953410560

(Formatted embeds are currently not supported)
infominer9/27/2018, 11:21:54 PM

https://twitter.com/CryptoQF/status/1042265797584797696

(Formatted embeds are currently not supported)
infominer9/29/2018, 12:58:52 AM

https://news.bitcoin.com/six-new-and-improved-cryptocurrency-analysis-tools/
infominer9/29/2018, 2:32:24 AM

https://medium.com/@cryptocreddy/does-technical-analysis-work-fa90413a8328
infominer9/30/2018, 4:16:44 PM

plenty of trading books https://t.me/LibTA
infominer9/30/2018, 7:54:53 PM

https://github.com/hientm36/gnidart
infominer9/30/2018, 11:29:05 PM

https://twitter.com/JimAllmendinger/status/1044710492923617281

(Formatted embeds are currently not supported)
infominer10/4/2018, 4:45:01 PM

https://tensorcharts.com/
https://aggr.trade/#
infominer10/4/2018, 4:46:10 PM

https://www.marketvolume.com/technicalanalysis/rating.asp
infominer10/4/2018, 4:52:19 PM

https://cryptowest.com/books-trading-tools/
infominer10/4/2018, 4:53:18 PM

https://cryptowest.com/2018/08/24/one-important-concepts-trading/
infominer10/4/2018, 8:28:11 PM

https://www.youtube.com/watch?v=Ou_BPr84GHY
infominer10/7/2018, 6:13:08 PM

https://medium.com/@ThinkingUSD/deribit-bitcoin-options-and-volatility-b370ba276761
infominer10/8/2018, 1:19:21 AM

https://drive.google.com/file/d/1Ew_O4fMdGM2M8NhYDFB0NJmLMCIQi-Tl/view
infominer10/8/2018, 1:36:30 AM

https://app.compound.finance/
infominer10/8/2018, 9:33:45 AM(edited)

https://avc.com/2018/10/fully-diluted-market-value/
infominer10/11/2018, 3:02:34 PM

https://medium.com/@cryptocreddy/comprehensive-guide-to-position-size-and-leverage-2e27764ce9e0
infominer10/12/2018, 1:53:14 AM(edited)

that's the shape of about to moon
(image attachment not found)
