# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Source Crypto"
rooturl                  : "https://infominer.id/SourceCrypto"
title_separator          : "⧉ "
name                     : "Infominer"
description              : Chat Server for Creating an Open-Source Database of Crypto Knowledge.
url                      : https://infominer.id
baseurl                  : "/SourceCrypto"
repository               : "infominer33/SourceCrypto"
github                   : [metadata]
teaser                   : # /assets/images/500x300.png
logo                     : "https://infominer.id/SourceCrypto/assets/icons/source.png"
masthead_title           : Research Index — Source ⧉ Crypto — Discord Chat.
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : # true
search_provider          : algolia
algolia:
  application_id         : 7SQ04IUKA2
  index_name             : Source
  search_only_api_key    : 83b0540a06db15322d3c5231fb605aad
  powered_by             : true
  files_to_exclude:
    - _includes/*
    - _layouts/*
  extensions_to_index:
    - 'html'
    - 'md'
    - 'json'

google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : infominer33
  title                  : "Source ⧉ Crypto"
  description            : Chat Server for Creating an Open-Source Database of Crypto Knowledge.
  image                  : "https://infominer.id/SourceCrypto/assets/img/SourceCrypto.png"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "https://infominer.id/SourceCrypto/assets/img/SourceCrypto.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-132558656-1
    anonymize_ip         : # true, false (default)

author:
  name:                
  email:               
  twitter:             infominer33

# Site Author
author:
  name             : "⧉ Infominer"
  avatar           : "/assets/img/bio-photo2.jpg"
  links:
    - label: "Inf⧉Mine"
      icon: "fa fa-fw fa-cube"
      url: "https://infominer.id"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:infominer@protonmail.com"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url:  "https://keybase.io/infominer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/infominer33/SourceCrypto"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/infominer33"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/ahTuPMY"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/InfoMiner33"
   # - label: "Bitcoin"
    #  icon: "fab fa-fw fa-bitcoin"
     # url: 

# Site Footer
footer:
  links:
    - label: "Inf⧉Mine"
      icon: "fa fa-fw fa-cube"
      url: "https://infominer.id"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:infominer@protonmail.com"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url:  "https://keybase.io/infominer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/infominer33/SourceCrypto"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/infominer33"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/ahTuPMY"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/InfoMiner33"


# Reading Files
include:
  - .htaccess
  - _pages
  - discolog
  - practical
  - toml
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Collections
collections_dir: discolog
collections:
  general:
    title: General Knowledge
    description: For information broadly related to all cryptocurrency and blockchain.
    output: true
    order: 1
    permalink: /discolog/:collection/:path/
  resources:
    title: Resources Channels
    descrioption: For collections of resources.
    order: 2
    output: true
    permalink: /discolog/:collection/:path/
  privacy:
    title: Privacy Preserving Technolgy
    description: Cause govts don't want you to
    order: 3
    output: true
    permalink: /discolog/:collection/:path/
  crypto:
    title: Crypto(currency) 
    description: For cryptocurrencies, and popular cryptographyic systems
    order: 4
    output: true
    permalink: /discolog/:collection/:path/
  consensus:
    title: Channels for Blockchain Consensus
    description: PoW, PoS, PoEverything Else
    order: 5
    output: true
    permalink: /discolog/:collection/:path/
  tech:
    title: Technologies Related to Bitcoin
    description: tech tech tech
    order: 6
    output: true
    permalink: /discolog/:collection/:path/
  development:
    title: Blockchain Development
    description: For Building Blocks and Chains of BLocks
    order: 7
    output: true
    permalink: /discolog/:collection/:path/
  application:
    title: Blockchain Applications 
    description: There are many... I try to avoid thinkikng about ICOs
    order: 8
    output: true
    permalink: /discolog/:collection/:path/
  


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: # true
      read_time: # true
      comments: # true
      share: true
      related: true
      sidebar:
        nav: "sourcenav"
      toc: true
      toc_label   : "Contents"
      toc_icon    : "link"
      toc_sticky  : true
  # _general
  - scope:
      path: ""
      type: general
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _resources
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _crypto
  - scope:
      path: ""
      type: crypto
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _privacy
  - scope:
      path: ""
      type: privacy
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _consensus
  - scope:
      path: ""
      type: consensus
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _tech
  - scope:
      path: ""
      type: tech
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _development
  - scope:
      path: ""
      type: development
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
    # _application
  - scope:
      path: ""
      type: application
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        nav: "sourcenav"
      classes: wide
      disco: true
