# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

#theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Source Crypto"
title_separator          : "|"
name                     : "Infominer"
description              : Chat Server for Creating an Open-Source Database of Crypto Knowledge.
url                      : "https://sourcecrypto.pub"
baseurl                  : ""
repository               : "sourcecrypto/sourcecrypto.github.io"
github                   : [metadata]
teaser                   : /images/Source-Crypto-og.png
logo                     : "https://sourcecrypto.pub/images/interlinked.png"
masthead_title           : Research Index — Discord Chat
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : false
search_provider          : lunr
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
# Social Sharing
twitter:
  username               : SourceCrypto
  title                  : "Source ⧉ Crypto"
  description            : Chat Server for Creating an Open-Source Database of Crypto Knowledge.
  image                  : "https://SourceCrypto.pub/images/Square-Crypto.png"
og_image                 : "https://SourceCrypto.pub/images/Source-Crypto-og.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-132558656-5
    anonymize_ip         : true

# Site Author
author:
  name             : "⧉ Infominer"
  avatar           : "https://SourceCrypto.pub/images/bio-photo2.jpg"
  links:
    - label: "Info⧉Hub"
      icon: "fa fa-fw fa-cube"
      url: "https://infominer.id"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:infominer@protonmail.com"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url:  "https://keybase.io/infominer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sourcecrypto"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sourcecrypto"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/ahTuPMY"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/InfoMiner33"
   # - label: "Bitcoin"
    #  icon: "fab fa-fw fa-bitcoin"
     # url: 

# Site Footer
footer:
  links:
    - label: "Info⧉Hub"
      icon: "fa fa-fw fa-cube"
      url: "https://infominer.id"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:infominer@protonmail.com"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url:  "https://keybase.io/infominer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sourcecrypto"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/infominer33"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/ahTuPMY"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/InfoMiner33"


# Reading Files
include:
  - _posts/transcripts/
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /posts/:categories/:slug/
paginate: 8
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-twitter-plugin

jekyll-mentions:
  base_url: https://twitter.com

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-twitter-plugin

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  general:
    output: true
    permalink: /archive/:collection/:path/
    share: true
  resources:
    output: true
    permalink: /archive/:collection/:path/
    share: true
  crypto:
    output: true
    permalink: /archive/:collection/:path/
    share: true
  blockchaintech:
    output: true
    permalink: /archive/blockchain-tech/:path/
    share: true
  tech:
    output: true
    permalink: /archive/:collection/:path/
    share: true
  development:
    output: true
    permalink: /archive/:collection/:path/
    share: true
  enterprise:
    output: true
    permalink: /archive/:collection/:path/
    share: true
  application:
    output: true
    permalink: /archive/:collection/:path/
    share: true


# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      toc: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/source-crypto-gh-og.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
  # _general
  - scope:
      path: "_general"
      type: general
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/source-crypto-gh-og.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
  # _resources
  - scope:
      path: "_resources"
      type: resources
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/source-crypto-gh-og.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
    # _crypto
  - scope:
      path: "_crypto"
      type: crypto
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/crypto-teaser.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
    # _blockchaintech
  - scope:
      path: "_blockchaintech"
      type: blockchaintech
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/blockchain-tech-teaser.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
    # _tech
  - scope:
      path: "_tech"
      type: tech
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/tech-teaser-1.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
    # _development
  - scope:
      path: "_development"
      type: development
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/development.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
    # _enterprise
  - scope:
      path: "_enterprise"
      type: enterprise
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/source-crypto-gh-og.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
    # _application
  - scope:
      path: "_application"
      type: application
    values:
      layout: single
      share: true
      comment: true
      related: true
      sidebar:
        title: "⧉Info⧉"
        nav: "sourcedisco"
      classes: wide
      disco: true
      header:
       image: /images/Source-Crypto-banner.png
       teaser: /images/source-crypto-gh-og.png
       caption   : "@Delpadschnick | [CryptoDesign.io](https://CryptoDesign.io)"
