infominer9/27/2018, 10:57:28 PM
https://blog.neufund.org/good-protocols-how-to-properly-standardize-security-tokens-95ff83c81c4a

infominer9/28/2018, 8:13:57 PM
https://www.ccn.com/how-to-write-an-sto-white-paper-a-step-by-step-guide-part-i/

infominer9/30/2018, 3:10:45 AM
https://blog.nomics.com/flippening/security-token-documentary/

infominer10/7/2018, 12:15:20 AM
https://youtu.be/SktQfwjQ6jw

infominer10/11/2018, 9:47:44 PM
https://medium.com/@tatianakoffman/your-official-guide-to-the-security-token-ecosystem-61a805673db7

infominer10/11/2018, 9:48:13 PM
https://medium.com/@apompliano/the-official-guide-to-tokenized-securities-44e8342bb24f

infominer10/11/2018, 9:48:24 PM
https://medium.com/@jrodthoughts/security-token-2-0-some-thoughts-off-chain-vs-on-chain-governance-2cba087389ab

infominer10/11/2018, 9:48:31 PM
https://hackernoon.com/security-tokens-2-0-about-on-chain-governance-part-ii-ca9378cea172

infominer10/11/2018, 9:49:19 PM
https://token.security/

infominer10/11/2018, 9:49:57 PM
https://twitter.com/SecTokenNetwork

Security Token Network (@SecTokenNetwork)
No BS, no hype, just fundamentals. Latest news from across the #SecurityToken #STO and #Blockchain industry. Analysis by successful entrepreneurs and VC’s.

infominer11/25/2018, 7:48:39 PM
https://medium.com/@apompliano/the-sec-will-mandate-security-tokens-ee3312c6fea7

infominer12/23/2018, 12:52:56 AM
https://bitcoinist.com/sto-sexier-ico-end/

infominer12/23/2018, 1:11:06 AM
https://medium.com/atomic-capital/state-of-the-standards-a-technical-review-of-current-digital-securities-standards-3bc79f5aaf73