[Title]<br/>
Link = "Blah.com"<br/>
Author = "blah"<br/>
Source = "blah blah"<br/>
Description = "Blah blah \n blah blah"<br/>
Tags = ["Blah", "Blah-blah"]

\\example ^^^

[Cryptocurrency 101]
Link = "https://medium.com/@intenex/cryptocurrency-101-7197684775fd"
Author = "Ben Yu"
Source = "Medium.com"
Description = "The first part will speak to a broad explanation of what bitcoin and cryptocurrency at large are. The second will discuss my personal investment philosophy as it pertains to crypto. The third will show you step by step how to actually begin investing in crypto, if you so choose. Each section will be clearly delineated, so feel free to skip parts if they’re already familiar to you."
Tags = ["101", "traditional-finance"]

[Blockchain In a Nutshell]
Link = "https://medium.com/@marcosallendelopez/blockchain-in-a-nutshell-38e7a566eac1"
Author = "Marcos Allende Lopez"
Source = "medium.com"
Description = "1. Most articles explain Blockchain only related to cryptocurrencies like Bitcoin without giving a clear idea of how it works (what is the consensus protocol, how are the blocks validated, how to get bitcoins, …). We’ll answer these questions here.\n
Most articles don’t talk about the other types of blockchains that are currently populating the internet and coming up in many conversations between CEOs. These are the private/federated ones. Below you will find answers to what these are, and how they are different from public blockchain networks (like Bitcoin or Ethereum)."
Tags = ["101"]

[Bitcoin, Blockchain, and Cryptocurrency]
Link = "https://www.csbtechemporium.com/bitcoin-blockchain-cryptocurrency/"
Author = "InfoMiner"
Source = "CSB Tech Emporium"
Description = "Provides a broad overview of and introduction to Bitcoin's background, history, how it works, the rise of cryptocurrencies, 2nd and 3rd gen blockchain, regulation, and a light speculation on the future of this new market."
Tags = ["101"]

[Blockchain Demo]
Link = "https://anders.com/blockchain/"
Author = "Anders Brownworth"
Source = "anders.com"
Description = "A visiual walkthrough of blockchain's technical specifications"
Tags = ["101", "Video"]

[The Hard Thing About Learning Hard Things]
Link = "https://medium.freecodecamp.org/the-hard-thing-about-learning-hard-things-168e655ac7f2"
Author = "Haseeb Qureshi"
Source = "freecodecamp.org"]
Description = "How do you learn something no one can teach you?\n\n

Whatever success I’ve had in my career, I attribute almost entirely to my aptitude for unstructured learning. This is the kind of learning required when delving into a cutting-edge field, navigating a new job, or creating anything genuinely new. Notably, it’s the polar opposite of what is taught in schools and what most people call “education.”"
tags = ["101", "developing", "tech"]

[Bitcoin and Cryptocurrency Technologies Online Course]
Link = "https://www.youtube.com/playlist?list=PLQIX_E46U4XYE5GR6029FpnaX9aBXbt0B"
Author = "Harold Hesh Frydman"
Source = "Princeton"
Description = "A series of lectures offering an introduction into the world of cryptocurrency:\n
Lecture 1 — Intro to Crypto and Cryptocurrencies\n
Lecture 2 — How Bitcoin Achieves Decentralization\n
Lecture 3 — Mechanics of Bitcoin\n
Lecture 4 — How to Store and Use Bitcoins\n
Lecture 5 — Bitcoin Mining\n
Lecture 6 — Bitcoin and Anonymity\n
Lecture 7 — Community, Politics, and Regulation\n
Lecture 8 — Alternative Mining Puzzles\n
Lecture 9 — Bitcoin as a Platform\n
Lecture 10 — Altcoins and the Cryptocurrency Ecosystem\n
Lecture 11 — The future of Bitcoin?\n
Lecture 12 — History of Cryptocurrencies [Bonus lecture]"
tags = ["101", "video", "history"]

[99bitcoins.com]
Link = "https://99bitcoins.com"
Description = "Buy Bitcoin, Bitcoin Guides & Reviews for Bitcoin Newbies"
Tags = ["101"]

---

https://azeria-labs.com/the-importance-of-deep-work-the-30-hour-method-for-learning-a-new-skill/

---

https://www.csbtechemporium.com/research/blockchain/where-to-buy-bitcoin-and-other-cryptocurrencies/

---

https://www.smithandcrown.com/research/

---

https://www.theverge.com/2018/3/7/17091766/blockchain-bitcoin-ethereum-cryptocurrency-meaning

---

https://coincenter.org/entry/what-is-a-51-attack-and-what-can-a-successful-attacker-do-1

---

https://files.stlouisfed.org/files/htdocs/publications/review/2018/01/10/a-short-introduction-to-the-world-of-cryptocurrencies.pdf

---

http://unchainedpodcast.co/crypto-101-everything-you-need-to-know-about-bitcoin-ethereum-blockchains-icos-and-more

---

http://fortune.com/2018/09/05/blockchain-coursera/

---

https://youtu.be/3zdlOkC8uOw

---

https://coindoo.com/in-depth-analysis-what-is-a-bitcoin-block/

---

https://a16z.com/2018/02/10/crypto-readings-resources/

---

https://hackernoon.com/why-bitcoin-why-sooner-rather-than-later-e44aa5373479

---

https://www.youtube.com/watch?v=_160oMzblY8

---

https://www.coursera.org/learn/blockchain-foundations-and-use-cases

---

https://medium.com/@fayehays/visual-crypto-vol-1-acronyms-2674a80bba7

---

https://twitter.com/oleganza/status/1034178524389634048

---

https://www.blockchainedu.org/education/

---

https://twitter.com/The1Brand7/status/989449833302953984

---

http://bitcoin.org

---

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2832751

---

https://blog.xapo.com/why-own-bitcoin/

---

https://coincenter.org/entry/do-you-really-need-a-blockchain-for-that

---

https://cryptominded.com/glossary-cryptocurrency-terms-need-know/

---

https://medium.com/@jimmysong/why-blockchain-is-hard-60416ea4c5c

---

https://www.axiomtech.io/blog-feed/2018/10/9/smart-contracts-uses-cases-dapps-icos

---

https://twitter.com/Bitboy_Hodl/status/1050235145733791744

---

https://github.com/0xtokens/awesome-blockchain#whats-cooking
